{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.lifecycle",
    "module": "lifecycle-viewmodel-ktx",
    "version": "2.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.1.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.1.aar",
          "size": 4024,
          "sha512": "d96519c2824ec27ff347c5a5c0fd2d1cb138787eacef838bf11b75bb269aad8095753c3f575fe352186ed3563a0c94ca4fdee8ac6a0b5a9ac5789cb0bfa61bb4",
          "sha256": "30eecb351d81f0c429e186e65a892a42ce1d5bc5c80420bfece4ae279333023d",
          "sha1": "029568ba92f7069ecf00949f74898f57e61d40d4",
          "md5": "4167b1a439be9f530c5cbf26b590e5cb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.1.aar",
          "url": "lifecycle-viewmodel-ktx-2.5.1.aar",
          "size": 4024,
          "sha512": "d96519c2824ec27ff347c5a5c0fd2d1cb138787eacef838bf11b75bb269aad8095753c3f575fe352186ed3563a0c94ca4fdee8ac6a0b5a9ac5789cb0bfa61bb4",
          "sha256": "30eecb351d81f0c429e186e65a892a42ce1d5bc5c80420bfece4ae279333023d",
          "sha1": "029568ba92f7069ecf00949f74898f57e61d40d4",
          "md5": "4167b1a439be9f530c5cbf26b590e5cb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lifecycle-viewmodel-ktx-2.5.1-sources.jar",
          "url": "lifecycle-viewmodel-ktx-2.5.1-sources.jar",
          "size": 1410,
          "sha512": "bfe6372c5910f626e7b41bb6468d62612d1f1bde9b3c767caaa7eb7c07e93cf00d047d8e909b7c47f2985f42ffa554a82888f83e712473cee8756407fcc09548",
          "sha256": "8af8f2ac694742fe8ae133067dfdec6a193a738f46ba80c59b3e8a4ab36703f3",
          "sha1": "a900dc99643d8638beb02bd809a495f772d457e7",
          "md5": "43d89db66da712ab2560a41753632946"
        }
      ]
    }
  ]
}