{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.navigation",
    "module": "navigation-fragment-ktx",
    "version": "2.5.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5-20220421031748+0000"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.5.2.aar",
          "url": "navigation-fragment-ktx-2.5.2.aar",
          "size": 1777,
          "sha512": "e7abd0586682fdfe3dc55aefa486842a2df2af87fc8e33c452ec23897db6a8b46ac2e83578814071c84c48ad1c75b2719b268d63d516074a27beb5aed5125016",
          "sha256": "242f5e24591d299811920cc53d7302b8bf9f7beb4f35bac90510ed4273e591cb",
          "sha1": "8b614a6e9fa436ed777c3da5b72cc89b55c92643",
          "md5": "26af56f8227a248a86c21d564f06b02d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.navigation",
          "module": "navigation-fragment",
          "version": {
            "requires": "2.5.2"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-runtime-ktx",
          "version": {
            "requires": "2.5.2"
          },
          "reason": "Mirror navigation-fragment dependency graph for -ktx artifacts"
        }
      ],
      "files": [
        {
          "name": "navigation-fragment-ktx-2.5.2.aar",
          "url": "navigation-fragment-ktx-2.5.2.aar",
          "size": 1777,
          "sha512": "e7abd0586682fdfe3dc55aefa486842a2df2af87fc8e33c452ec23897db6a8b46ac2e83578814071c84c48ad1c75b2719b268d63d516074a27beb5aed5125016",
          "sha256": "242f5e24591d299811920cc53d7302b8bf9f7beb4f35bac90510ed4273e591cb",
          "sha1": "8b614a6e9fa436ed777c3da5b72cc89b55c92643",
          "md5": "26af56f8227a248a86c21d564f06b02d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navigation-fragment-ktx-2.5.2-sources.jar",
          "url": "navigation-fragment-ktx-2.5.2-sources.jar",
          "size": 261,
          "sha512": "747d2f00a7f5f379582e33e452f30f3a25732a510971d9ed5161355bf7ef0fc507fef30883960dbfc780d36b6e8215fba01086b4ee053358805686e2f2c1aa85",
          "sha256": "69e1a62e5752ca3f43fb1607f161379bbe88b64af89c1a543c126160adf7cc53",
          "sha1": "5b8f86fea035328fc9e8c660773037a3401ce25f",
          "md5": "e7e9f45eb9d74540092920528bb0abf0"
        }
      ]
    }
  ]
}